### ISSUE TITLE
pip-tools==7.4.0

### ISSUE THREAD

**Issue by obi-defra** [Defra-Data-Science-Centre-of-Excellence/init-scripts#49]
Add installation of pip-tools==7.4.0 to DASH.ini init script.

**Comment by pantelisindefra** [comment]
Hello @obi-defra We don't fix versions in general. But happy to add `pip-tools`.

**Comment by obi-defra** [comment]
That works! Thank you

**Comment by aw-west-defra** [comment]
Resolved with #50 closing
